---
version: '3'
services:
  node-app:
    build:
      context: .
    image: node-cmd-image
    container_name: nodex
    ports:
      - "4000:3500"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    stdin_open: true
    tty: true
