# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_BOX = 'almalinux/8'

Vagrant.configure("2") do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = "almalinux8-jumpbox.local"
  config.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz", ip: "192.168.50.206", hostname: true
  config.vm.network "private_network", ip: "10.10.10.206"
  config.vm.network "forwarded_port", id: "ssh", host_ip: "127.0.0.1", host: 2206, guest: 22
  config.ssh.private_key_path = "~/.vagrant.d/id_rsa"
  config.ssh.forward_agent = true
  config.vm.provider "virtualbox" do |vm|
    vm.name = "almalinux8-jumpbox"
    vm.cpus = 2
    vm.memory = "2048"
    vm.linked_clone = true
    vm.check_guest_additions = false
  end
  config.vm.provision "shell", path: "install-this.sh"
end
